
import { Translation } from './types';

const EN_CASE_STUDIES = {
  "tourism": {
    id: "tourism",
    title: "Vila Falo Voskopoje",
    clientType: "Historic Boutique Hotel",
    heroImage: "gradient-to-br from-stone-800 to-stone-900",
    problem: {
      title: "Weekend Surge Chaos",
      desc: "Located in the heart of Voskopoje, Vila Falo faced overwhelming demand every Friday and Saturday. Staff struggled to juggle restaurant service, physical check-ins, and ringing phones, resulting in 60% missed calls."
    },
    solution: {
      title: "AI Receptionist Core",
      desc: "We deployed a hybrid Voice & Chat AI trained specifically on the Korça dialect. It autonomously handles availability checks, pricing inquiries, and sends location pins via WhatsApp.",
      steps: [
        { title: "Dialect NLP Model", desc: "Fine-tuned to understand local phrases like 'A keni dhoma?' and specific Voskopoje accents." },
        { title: "Calendar Guard", desc: "Real-time bi-directional sync with Booking.com to prevent double bookings during surges." },
        { title: "Smart Guide", desc: "Upon booking, the AI automatically sends the Google Maps pin and parking instructions." }
      ]
    },
    results: [
      { value: "100%", label: "Calls Answered" },
      { value: "Auto", label: "Weekend Booking" },
      { value: "0", label: "Double Bookings" }
    ]
  },
  "realestate": {
    id: "realestate",
    title: "Tirana Property Flow",
    clientType: "Real Estate Agency",
    heroImage: "gradient-to-br from-emerald-900 to-black",
    problem: {
      title: "Lead Fatigue",
      desc: "Agents were spending 4 hours a day answering 'Is this available?' and 'What is the price?' instead of closing deals. High value clients were getting lost in the noise."
    },
    solution: {
      title: "Global Standard Qualification",
      desc: "A smart CRM automation that engages leads instantly, qualifies their budget and timeline, and only alerts agents for serious buyers.",
      steps: [
        { title: "Lead Capture", desc: "AI scrapes leads from Facebook, Instagram, and Web forms instantly." },
        { title: "Smart Filtering", desc: "The bot chats with the lead to determine budget, location preference, and readiness." },
        { title: "Agent Dispatch", desc: "High-value leads are booked directly into the agent's Google Calendar." }
      ]
    },
    results: [
      { value: "24/7", label: "Lead Processing" },
      { value: "4h", label: "Saved Per Agent/Day" },
      { value: "2x", label: "Viewing Conversion" }
    ]
  },
  "ecommerce": {
    id: "ecommerce",
    title: "Retail Personalization",
    clientType: "Fashion E-Commerce",
    heroImage: "gradient-to-br from-purple-900 to-black",
    problem: {
      title: "Cart Abandonment",
      desc: "Users were browsing but not buying. The generic experience failed to guide customers to products they actually liked."
    },
    solution: {
      title: "AI Shopping Assistant",
      desc: "A recommendation engine that analyzes user behavior in real-time to suggest outfits, not just products.",
      steps: [
        { title: "Behavior Analysis", desc: "Tracking clicks and hover times to build a style profile." },
        { title: "Visual Search", desc: "Users can upload photos of styles they like, and AI finds matching stock." },
        { title: "Dynamic Recovery", desc: "Personalized email sequences generated by AI for abandoned carts." }
      ]
    },
    results: [
      { value: "18%", label: "Revenue Increase" },
      { value: "45%", label: "Less Cart Abandonment" },
      { value: "Auto", label: "Inventory Mgmt" }
    ]
  },
  "legal": {
    id: "legal",
    title: "Legal Document Core",
    clientType: "Corporate Law Firm",
    heroImage: "gradient-to-br from-neutral-800 to-neutral-900",
    problem: {
      title: "Document Overload",
      desc: "Lawyers were drowning in paperwork, spending days reviewing standard contracts manually."
    },
    solution: {
      title: "Contract Analysis Engine",
      desc: "NLP system that reviews contracts, highlights risks, and drafts standard clauses automatically.",
      steps: [
        { title: "OCR & Digitization", desc: "Converting paper archives to searchable vector databases." },
        { title: "Risk Detection", desc: "AI flags clauses that deviate from standard Albanian law." },
        { title: "Draft Generation", desc: "Lawyers dictate requirements; AI writes the first draft." }
      ]
    },
    results: [
      { value: "80%", label: "Faster Drafting" },
      { value: "0", label: "Gabime Formati" },
      { value: "100%", label: "Searchable Archive" }
    ]
  },
  "healthcare": {
    id: "healthcare",
    title: "Clinic Flow OS",
    clientType: "Private Polyclinic",
    heroImage: "gradient-to-br from-cyan-900 to-blue-900",
    problem: {
      title: "Patient Scheduling Chaos",
      desc: "Reception was overwhelmed with calls, leading to double bookings and missed appointment reminders."
    },
    solution: {
      title: "Smart Health Desk",
      desc: "Voice and Text AI agent that manages the entire patient intake flow.",
      steps: [
        { title: "Voice AI", desc: "An AI phone agent that answers calls and speaks natural Albanian." },
        { title: "Calendar Sync", desc: "Integrates with doctor schedules to find open slots instantly." },
        { title: "WhatsApp Reminders", desc: "Automated follow-ups reduced no-shows significantly." }
      ]
    },
    results: [
      { value: "95%", label: "Call Answer Rate" },
      { value: "60%", label: "Fewer No-Shows" },
      { value: "24/7", label: "Patient Support" }
    ]
  }
};

const SQ_CASE_STUDIES = {
  "tourism": {
    id: "tourism",
    title: "Vila Falo Voskopojë",
    clientType: "Hotel Historik",
    heroImage: "gradient-to-br from-stone-800 to-stone-900",
    problem: {
      title: "Kaosi i Fundjavës",
      desc: "E vendosur në zemër të Voskopojës, Vila Falo përballej me kërkesë masive çdo fundjavë. Stafi e kishte të pamundur të shërbente në restorant dhe të përgjigjej në telefon, duke humbur 60% të rezervimeve."
    },
    solution: {
      title: "Recepsionist Digjital Hibrid",
      desc: "Ne instaluam një sistem të Inteligjencës Artificiale që menaxhon telefonatat dhe mesazhet në dialektin e Korçës. Ajo kontrollon dhomat e lira, negocion çmimet dhe dërgon automatikisht vendndodhjen.",
      steps: [
        { title: "Model Dialekti NLP", desc: "I trajnuar për të kuptuar 'A keni dhoma?' dhe nuancat e zonës së Voskopojës." },
        { title: "Mbrojtje Kalendari", desc: "Sinkronizim në kohë reale me Booking.com për të shmangur mbivendosjet." },
        { title: "Udhërrëfyes Smart", desc: "Me konfirmimin e rezervimit, Inteligjenca Artificiale dërgon automatikisht Pin-in dhe udhëzimet e parkimit." }
      ]
    },
    results: [
      { value: "100%", label: "Thirrje të Përgjigjura" },
      { value: "Auto", label: "Rezervime Fundjave" },
      { value: "0", label: "Rezervime të Dyfishta" }
    ]
  },
  "realestate": {
    id: "realestate",
    title: "Tirana Property Flow",
    clientType: "Agjenci Imobiliare",
    heroImage: "gradient-to-br from-emerald-900 to-black",
    problem: {
      title: "Lodhja nga Mesazhet",
      desc: "Agjentët shpenzonin 4 orë në ditë duke u përgjigjur 'A është e lirë?' dhe 'Sa kushton?' në vend që të mbyllnin shitje."
    },
    solution: {
      title: "Kualifikim Standard Global",
      desc: "Një CRM inteligjente që angazhohet me klientët, kualifikon buxhetin dhe njofton agjentët vetëm për blerësit seriozë.",
      steps: [
        { title: "Kapja e Klientit", desc: "Inteligjenca Artificiale mbledh kërkesat nga Facebook, Instagram dhe Web në moment." },
        { title: "Filtrimi Inteligjent", desc: "Boti bisedon për të përcaktuar buxhetin dhe preferencat." },
        { title: "Organizimi i Agjentit", desc: "Klientët seriozë prenotohen direkt në kalendarin e agjentit." }
      ]
    },
    results: [
      { value: "24/7", label: "Procesim Kërkesash" },
      { value: "4h", label: "Kursim ditor/agjent" },
      { value: "2x", label: "Konvertime Vizitash" }
    ]
  },
  "ecommerce": {
    id: "ecommerce",
    title: "Retail Personalization",
    clientType: "E-Commerce Veshjesh",
    heroImage: "gradient-to-br from-purple-900 to-black",
    problem: {
      title: "Braktisja e Shportës",
      desc: "Përdoruesit shikonin por nuk blinin. Eksperienca gjenerike dështonte t'i drejtonte te produktet që pëlqenin."
    },
    solution: {
      title: "Asistent Blerjesh AI",
      desc: "Një motor rekomandimesh që analizon sjelljen në kohë reale për të sugjeruar veshje, jo thjesht produkte.",
      steps: [
        { title: "Analiza e Sjelljes", desc: "Gjurmim i klikimeve për të krijuar profilin e stilit." },
        { title: "Kërkim Vizual", desc: "Përdoruesit ngarkojnë foto të stileve dhe Inteligjenca Artificiale gjen stokun." },
        { title: "Rikuperim Dinamik", desc: "Email-e të personalizuara nga Inteligjenca Artificiale për shportat e braktisura." }
      ]
    },
    results: [
      { value: "18%", label: "Rritje e Të Ardhurave" },
      { value: "45%", label: "Më Pak Braktisje" },
      { value: "Auto", label: "Menaxhim Stoku" }
    ]
  },
  "legal": {
    id: "legal",
    title: "Legal Document Core",
    clientType: "Studio Ligjore",
    heroImage: "gradient-to-br from-neutral-800 to-neutral-900",
    problem: {
      title: "Mbingarkesa me Letra",
      desc: "Avokatët po mbyteshin në dokumente, duke shpenzuar ditë të tëra për rishikime manuale kontratash."
    },
    solution: {
      title: "Motor Analize Kontratash",
      desc: "Sistem NLP që rishikon kontratat, evidenton rreziqet dhe harton klauzola standarde automatikisht.",
      steps: [
        { title: "Digjitalizimi", desc: "Kthimi i arkivave në baza të dhënash të kërkueshme." },
        { title: "Detektimi i Rrezikut", desc: "Inteligjenca Artificiale shënjon klauzolat që devijojnë nga ligji shqiptar." },
        { title: "Gjenerim Drafti", desc: "Avokatët diktojnë kërkesat; Inteligjenca Artificiale shkruan draftin e parë." }
      ]
    },
    results: [
      { value: "80%", label: "Hartim më i Shpejtë" },
      { value: "0", label: "Gabime Formati" },
      { value: "100%", label: "Arkivë Inteligjente" }
    ]
  },
  "healthcare": {
    id: "healthcare",
    title: "Clinic Flow OS",
    clientType: "Private Polyclinic",
    heroImage: "gradient-to-br from-cyan-900 to-blue-900",
    problem: {
      title: "Patient Scheduling Chaos",
      desc: "Reception was overwhelmed with calls, leading to double bookings and missed appointment reminders."
    },
    solution: {
      title: "Smart Health Desk",
      desc: "Voice and Text AI agent that manages the entire patient intake flow.",
      steps: [
        { title: "Voice AI", desc: "An AI phone agent that answers calls and speaks natural Albanian." },
        { title: "Calendar Sync", desc: "Integrates with doctor schedules to find open slots instantly." },
        { title: "WhatsApp Reminders", desc: "Automated follow-ups reduced no-shows significantly." }
      ]
    },
    results: [
      { value: "95%", label: "Call Answer Rate" },
      { value: "60%", label: "Fewer No-Shows" },
      { value: "24/7", label: "Patient Support" }
    ]
  }
};

export const CONTENT: Record<string, Translation> = {
  en: {
    nav: {
      home: "Home",
      services: "Services",
      useCases: "Case Studies",
      about: "About Us",
      contact: "Contact",
      bookBtn: "Book Consultation",
      backBtn: "Back to Home"
    },
    hero: {
      badge: "GLOBAL STANDARDS IN ALBANIA",
      headline: "Bringing Global Tech to Your Business",
      subheadline: "We bring global technology to your business. Enterprise-grade AI used by the world's largest corporations, now in Tirana.",
      ctaPrimary: "Start Transformation",
      ctaSecondary: "View Case Studies",
      techText: "Powered by Global Tech Standards:"
    },
    stats: [
      { label: "Global Expertise", value: "100%" },
      { label: "Hours Saved", value: "20h+" },
      { label: "ROI Increase", value: "10x" },
    ],
    about: {
      title: "World-Class Expertise",
      description: "We are not just a local agency. We help Albanian businesses implement intelligent systems tailored to every business. My goal is not to sell you software, but to build systems that solve your real problems.",
      cards: [
        { title: "Global Standards", desc: "Implementing Western data privacy and efficiency protocols." },
        { title: "World-Class Tech", desc: "The same AI engines used by global market leaders." },
        { title: "Local Impact", desc: "We speak Albanian, but we build with a global mindset." },
      ]
    },
    services: {
      title: "World-Class Ecosystem",
      subtitle: "Our Capabilities",
      items: [
        { title: "AI Powered Websites", desc: "Websites that adapt to visitors in real-time. They don't just display info; they converse, convert, and close sales automatically.", icon: "Monitor" },
        { title: "Digital Assistant 24/7", desc: "An employee who never sleeps, speaks fluent Albanian, and answers hundreds of clients simultaneously.", icon: "MessageCircle" },
        { title: "Eliminating Manual Work", desc: "From Excel to invoices. If a task is repeated, we automate it quickly.", icon: "Zap" },
        { title: "AI Marketing & CRM", desc: "Automated campaigns, smart customer targeting, and CRM systems that nurture leads for you.", icon: "TrendingUp" },
        { title: "Data-Driven Decisions", desc: "Don't guess. Understand exactly what your customers want based on real statistics.", icon: "Database" },
      ],
      cta: "Explore All Solutions"
    },
    demos: {
      subtitle: "Live Demonstration",
      title: "See the Power",
      smartAgent: {
        title: "Smart Assistants",
        desc: "24/7 client support fluent in Albanian & English.",
        stats: "100% Availability",
        systemLabel: "AI Powered Response System"
      },
      automation: {
        title: "Instant Workflow",
        desc: "Seamless connection between social media and your billing system."
      },
      booking: {
        title: "Smart Calendar",
        desc: "AI fills your schedule, prevents double-booking, and ensures you never miss a client.",
        notification: "New Client Confirmed: 14:00"
      },
      growth: {
        title: "Revenue Growth",
        desc: "Strategies optimized for maximum ROI.",
        revenue: "Revenue",
        efficiency: "Efficiency"
      }
    },
    useCases: {
      subtitle: "Proven Results",
      title: "Real World Case Studies",
      cases: [
        { id: "tourism", title: "Vila Falo Voskopoje", category: "Hospitality", desc: "Auto-booking agents and dialect-aware guest support.", stats: "100% Calls" },
        { id: "realestate", title: "Real Estate", category: "Property", desc: "Lead qualification bots that schedule viewings automatically.", stats: "24/7 Availability" },
        { id: "ecommerce", title: "E-Commerce", category: "Retail", desc: "Personalized product recommendations and automated inventory.", stats: "2x Conversion" },
        { id: "legal", title: "Legal & Finance", category: "Professional", desc: "Document analysis and contract drafting assistance.", stats: "80% Time Saved" },
        { id: "healthcare", title: "Healthcare", category: "Medical", desc: "Automated patient scheduling and record organization compliant with regulations.", stats: "100% Compliant" }
      ],
      details: EN_CASE_STUDIES
    },
    reviews: {
      subtitle: "Client Testimonials",
      title: "Trusted by Visionaries",
      items: [
        {
          name: "Arben D.",
          role: "CEO",
          company: "Vila Falo",
          text: "The AI receptionist completely transformed our weekend chaos. We went from missing calls to 100% response rate instantly."
        },
        {
          name: "Elona K.",
          role: "Director",
          company: "Tirana Properties",
          text: "Our agents now only talk to qualified leads. The AI filters out the noise and schedules viewings automatically."
        },
        {
          name: "Gentian M.",
          role: "Founder",
          company: "TechRetail",
          text: "Implementing the recommendation engine increased our sales by 18% in the first month. It's like magic."
        }
      ]
    },
    education: {
      title: "Leading the Change",
      desc: "AI is not just technology; it is the new standard of doing business. We are here to ensure Albanian companies are not left behind.",
      points: [
        "Dedicated to AI implementation for business.",
        "Implementing Western tech standards with Albanian tradition.",
        "Educating the market while delivering results."
      ],
      credentialCode: "GB",
      credentialLabel: "United Kingdom"
    },
    contact: {
      title: "Start Your Evolution",
      desc: "The future doesn't wait. Book a consultation with Albania's premier AI experts today.",
      form: {
        name: "Full Name",
        email: "Email Address",
        business: "Company Name",
        message: "What is your main business challenge?",
        submit: "Get Started"
      }
    },
    footer: {
      rights: "All Rights Reserved.",
      tagline: "Intelligent Solutions for Real Problems.",
      columns: {
        company: "Company",
        legal: "Legal",
        social: "Social"
      },
      links: {
          about: "Rreth Nesh",
          services: "Shërbimet",
          privacy: "Politika e Privatësisë",
          terms: "Kushtet e Përdorimit"
      }
    }
  },
  sq: {
    nav: {
      home: "Kreu",
      services: "Shërbimet",
      useCases: "Raste Studimore",
      about: "Rreth Nesh",
      contact: "Kontakt",
      bookBtn: "Rezervo Konsulencë",
      backBtn: "Kthehu në Kreu"
    },
    hero: {
      badge: "STANDARTE NDËRKOMBËTARE NË SHQIPËRI",
      headline: "Të parët në Shqipëri që sjellin Inteligjencën Artificiale",
      subheadline: "Ne sjellim teknologjinë globale në biznesin tuaj. Inteligjencë Artificiale e nivelit të lartë që përdoret nga korporatat më të mëdha në botë, tani në Tiranë.",
      ctaPrimary: "Fillo Transformimin",
      ctaSecondary: "Shiko Rastet Studimore",
      techText: "Teknologji e standardeve:"
    },
    stats: [
      { label: "Ekspertizë Globale", value: "100%" },
      { label: "Kursim Kohe", value: "20h+" },
      { label: "Rritje ROI", value: "10x" },
    ],
    about: {
      title: "Ekspertizë e Nivelit Botëror",
      description: "Ne nuk jemi thjesht një agjenci lokale. Ne ndihmojme bizneset shqiptare te implementojne sistemet inteligjente ne varesi te cdo biznesi. Qëllimi im nuk është t'ju shes softuerë, por t'ju ndërtoj sisteme që zgjidhin problemet reale tuaj.",
      cards: [
        { title: "Standarde Globale", desc: "Protokolle të sigurisë dhe efikasitetit të nivelit ndërkombëtar." },
        { title: "Teknologji Botërore", desc: "Të njëjtët motorë AI që përdorin kompanitë Fortune 500." },
        { title: "Impakt Lokal", desc: "Ne flasim shqip, por ndërtojmë me mentalitet global." },
      ]
    },
    services: {
      title: "Ekosistem i Standardit Global",
      subtitle: "Kapacitetet Tona",
      items: [
        { title: "Website me Inteligjencë Artificiale", desc: "Faqe interneti që përshtaten në kohë reale. Nuk tregojnë thjesht info; ato bisedojnë, konvertojnë dhe shesin automatikisht.", icon: "Monitor" },
        { title: "Asistenti Dixhital 24/7", desc: "Një punonjës që nuk fle kurrë, flet rrjedhshëm shqip, dhe u përgjigjet qindra klientëve njëkohësisht.", icon: "MessageCircle" },
        { title: "Eliminimi i Punës Manuale", desc: "Nga Excel-i te faturat. Nëse një detyrë përsëritet, ne nje automatizim te shpejte.", icon: "Zap" },
        { title: "Sisteme CRM & Marketing", desc: "Fushata të automatizuara, targetim inteligjent dhe sisteme CRM që ndjekin klientin për ju.", icon: "TrendingUp" },
        { title: "Vendimmarrje me Të Dhëna", desc: "Mos hamendësoni. Kuptoni saktësisht çfarë duan klientët tuaj bazuar në statistika reale.", icon: "Database" },
      ],
      cta: "Zbulo të Gjitha"
    },
    demos: {
      subtitle: "Demonstrim Live",
      title: "Fuqia e Inteligjencës Artificiale",
      smartAgent: {
        title: "Agjentë Inteligjentë",
        desc: "Suport 24/7 në Shqip & Anglisht.",
        stats: "100% Disponueshmëri",
        systemLabel: "AI Powered Response System"
      },
      automation: {
        title: "Punë e Automatizuar",
        desc: "Lidhje pa ndërprerje mes rrjeteve sociale dhe sistemit të shitjeve."
      },
      booking: {
        title: "Kalendar Inteligjent",
        desc: "Inteligjenca Artificiale mbush oraret, shmang përplasjet dhe sigurohet që të mos humbni asnjë klient.",
        notification: "Klient i Ri Konfirmuar: 14:00"
      },
      growth: {
        title: "Rritje Fitimi",
        desc: "Strategji të optimizuara për ROI maksimal.",
        revenue: "Të Ardhurat",
        efficiency: "Efikasiteti"
      }
    },
    useCases: {
      subtitle: "Rezultate të Provuara",
      title: "Raste Studimore Reale",
      cases: [
        { id: "tourism", title: "Vila Falo Voskopojë", category: "Mikpritje", desc: "Rezervime automatike dhe suport në dialekt për turistët.", stats: "100% Përgjigje" },
        { id: "realestate", title: "Real Estate", category: "Prona", desc: "Kualifikim klientësh dhe lënie orari për vizita në apartamente.", stats: "24/7 Aktiv" },
        { id: "ecommerce", title: "E-Commerce", category: "Shitje Online", desc: "Rekomandime produktesh dhe menaxhim stoku automatik.", stats: "2x Konvertime" },
        { id: "legal", title: "Ligj & Financë", category: "Profesionale", desc: "Analizë dokumentash dhe hartim kontratash automatik.", stats: "80% Kursim Kohe" },
        { id: "healthcare", title: "Kujdesi Shëndetësor", category: "Mjekësi", desc: "Planifikim automatik i pacientëve dhe organizim kartelash.", stats: "100% Konform" }
      ],
      details: SQ_CASE_STUDIES
    },
    reviews: {
      subtitle: "Dëshmitë e Klientëve",
      title: "Besuar nga Vizionarët",
      items: [
        {
          name: "Arben D.",
          role: "CEO",
          company: "Vila Falo",
          text: "Recepsionisti me Inteligjencë Artificiale transformoi plotësisht kaosin e fundjavës. Kaluam nga humbja e telefonatave në 100% përgjigje."
        },
        {
          name: "Elona K.",
          role: "Drejtoresha",
          company: "Tirana Properties",
          text: "Agjentët tanë tani flasin vetëm me klientë të kualifikuar. AI filtron zhurmën dhe planifikon vizita automatikisht."
        },
        {
          name: "Gentian M.",
          role: "Themelues",
          company: "TechRetail",
          text: "Implementimi i motorit të rekomandimeve rriti shitjet tona me 18% në muajin e parë. Është si magji."
        }
      ]
    },
    education: {
      title: "Duke Udhëhequr Ndryshimin",
      desc: "Inteligjenca Artificiale nuk është thjesht teknologji; është standardi i ri i të bërit biznes. Ne jemi këtu për të siguruar që kompanitë shqiptare të mos mbesin pas.",
      points: [
        "Dedikuar implementimit të Inteligjencës Artificiale për biznes.",
        "Duke implemenaur standardet teknologjike perëndimore me traditen shqiptare.",
        "Duke edukuar tregun ndërkohë që sjellim rezultate."
      ],
      credentialCode: "GB",
      credentialLabel: "Mbretëri e Bashkuar"
    },
    contact: {
      title: "Filloni Evolucionin Tuaj",
      desc: "E ardhmja nuk pret. Rezervoni një konsultë me ekspertët kryesorë të Inteligjencës Artificiale në Shqipëri sot.",
      form: {
        name: "Emri i Plotë",
        email: "Adresa Email",
        business: "Emri i Biznesit",
        message: "Cila është sfida juaj kryesore?",
        submit: "Fillo Tani"
      }
    },
    footer: {
      rights: "Të Gjitha Të Drejtat e Rezervuara.",
      tagline: "Zgjidhje Inteligjente për Probleme Reale.",
      columns: {
        company: "Kompania",
        legal: "Ligjore",
        social: "Sociale"
      },
      links: {
          about: "Rreth Nesh",
          services: "Shërbimet",
          privacy: "Politika e Privatësisë",
          terms: "Kushtet e Përdorimit"
      }
    }
  }
};
